import React from 'react'

const Keypad = (props) => {
  // boilerplate table header functional component
  // const handleChange = props.handleChange;

  // MAKE HANDLE CLICK AND HANDLE KEY PRESS FUNCTIONS
  return (
    <div className='keypad_container'>
      <div className='kb_row'>
        <button
          data-key='q'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          q
        </button>
        <button
          data-key='w'
          onClick={props.handleChange}
          onKeyPress={props.handleKeyPress}
        >
          w
        </button>
        <button
          data-key='e'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          e
        </button>
        <button
          data-key='r'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          r
        </button>
        <button
          data-key='t'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          t
        </button>
        <button
          data-key='y'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          y
        </button>
        <button
          data-key='u'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          u
        </button>
        <button
          data-key='i'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          i
        </button>
        <button
          data-key='o'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          o
        </button>
        <button
          data-key='p'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          p
        </button>
      </div>
      <div className='kb_row'>
        <div className='indent'></div>
        <button
          data-key='a'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          a
        </button>
        <button
          data-key='s'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          s
        </button>
        <button
          data-key='d'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          d
        </button>
        <button
          data-key='f'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          f
        </button>
        <button
          data-key='g'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          g
        </button>
        <button
          data-key='h'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          h
        </button>
        <button
          data-key='j'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          j
        </button>
        <button
          data-key='k'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          k
        </button>
        <button
          data-key='l'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          l
        </button>
        <div className='indent'></div>
      </div>
      <div className='kb_row last_row'>
        <button
          data-key='↵'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          ENTER
        </button>
        <button
          data-key='z'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          z
        </button>
        <button
          data-key='x'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          x
        </button>
        <button
          data-key='c'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          c
        </button>
        <button
          data-key='v'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          v
        </button>
        <button
          data-key='b'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          b
        </button>
        <button
          data-key='n'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          n
        </button>
        <button
          data-key='m'
          onClick={props.handleChange}
          onKeyDown={props.handleKeyPress}
        >
          m
        </button>
        <button
          data-key='Backspace'
          onClick={props.handeDelete}
          onKeyDown={props.handeDelete}
        >
          BKSP
        </button>

        {/* need handle delete function
            // backspace keycode = 8
            // enter keycode = 13
          */}
      </div>
    </div>
  )
}

export default Keypad
